### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by obayemi** [obayemi/rust_hello#3]
- [x] Refactor to helm (for better variables management) -> DO LATER, Probably won't do, check alternative
- [x] Add db (learn volume/volume claim / statefulsets) ( #7 )
- [x] local environmemtn (probably depends on helm for easy configuration on things like hostname) -> Will do later, depends on variable managerment for deployment
- [x] https ingress (add https ingress with certbot managed certificates) ( #5 )
